all:
	git submodule init && git submodule update
	echo installing oh-my-zsh...
	sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
	echo making directories...
	find . -type d -not -name . -a -not -regex "\./\.git\(/.*\)?" -print -exec mkdir -p ~/{} \;
	echo linking files...
	find . -type f -not -name "README.md" -a -not -name "Makefile" -a -not -regex "\./\.git\(/.*\)?" -a -not -name ".gitmodules" -print -exec ln -f -T '{}' ~/{} \;
